id: P009164
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:26:05.262643
source_metadata:
  id: bdr:W3CN5054
  title: ཚད་མ་རིག་པའི་གཏེར་གྱི་རྩ་བ།
  author: ''
  volumes:
    a81377e0add64934842a43ef89d5a187:
      image_group_id: I3CN5056
      title: ''
      volume_number: 1
      total_pages: 66
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
